name: firebase_auth_mocks
description: Mocks for Firebase Auth. Use this package with `google_sign_in_mocks` to write unit tests involving Firebase Authentication.
version: 0.5.2
homepage: http://blog.wafrat.com
repository: https://github.com/atn832/firebase_auth_mocks

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.0.1
  meta: ^1.1.8
  mockito: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  test: ^1.0.0
